export const languages = {
    en: {
        btnStarted: "GET STARTED", 
        header1: "Making industrial AI work in 2 weeks",
        text1: "We offer remote real-time support and fleet management for collaborative robots, as well as automated guided vehicles and drones with AI that perform bin picking, parcel handling in logistics, retail, e-commerce and agriculture",
        text2: "Increased system reliability is achieved by real-time mistake correction in robot operations by 'Human-In-The-Loop' remote assistance service. It is about solving tier 1 emergencies in 10 minutes without escalation to system integrator.",
        text3: "We reduce AI failure rate to 0.5% making it as reliable as on-site human workers. Direct robot piloting is also possible bridging the technology gap where full automation is not yet applicable.",
        header2: "Remote Robot Piloting Service",
        text4: "Fully autonomous robot design and deployment is a long and costly process. Even after being released, robots once meet obstacles they were not programmed or trained to handle.",
        text5: "Experienced remote robot pilots can help the robot to continue its mission by driving it manually through the tough path region. Then the robot continues operation. The data is automatically collected and used to update the robot's AI to make it smarter.",
        text6: "Having imperfect AI should not stop your business. It is predictable when supported.",
        header3: "Feasibility Study",
        text7: "Before making substantial investment in automation, risks and opportunities can be assessed by fixed-price consulting.",
        text8: "We use design thinking approach to provide data-driven feasibility study report so you have all the information to make emphasized decisions.",
        camera: "Camera",
        camera2: "at workplace",
        cloud: "Cloud",
        cloud2: "processing",
        analysis: "Analysis",
        automation: "Automation",
        design: "design",
        insights: "Insights",
        requirements: "Requirements",
        header4: "Solution Development",
        text9: "AI-based automation is hard to do alone. There are so many things to consider: AI vendor, system integrator, cloud infrastructure, maintenance.",
        text10: "Our experienced team can help you not only to understand the landscape of current automation opportunities but fit an optimal solution for your business.",
        text11: "We make robots and human work together safely.",
        header5: "Automate your business now, contact us",
        uploadVideo: "Upload video from your process to get started",
        addFiles: "Add video",
        submitBtn: "SUBMIT",
        name: "Your Name",
        email: "Your E-mail",
        reserved: "All rights reserved.",
    },
    ua: {
        btnStarted: "ПОЧАТИ", 
        header1: "Сервіс дистанційного керування роботами",
        text1: "Роботи зі штучним інтелектом на службі вашого бізнесу - це сьогодення. Безпілотні мобільні складські платформи та маніпулятори вже зараз комплектують замовлення, перевозять вантажі та виконують багато іншої корисної роботи",
        text2: "Під час роботи штучний інтелект (ШІ) розумних машин іноді стикається із ситуаціями, які не були наперед відомі розробникам. До прикладу, робот-навантажувач не може обійти новий тип перешкоди і зупиняється. Зволікання у вирішенні таких проблем можуть мати наслідком непрогнозовані затримки виробничого процесу",
        text3: "Ми забезпечуємо надійне функціонування роботизованих систем із ШІ через дистанційний моніторинг та пряме пілотування. Досвідчений пілот, що безперервно спостерігає за робочим процесом через 'очі робота', здатен швидко обійти перешкоду, зібрати складне замовлення чи викликати технічний персонал",
        header2: "Сервіс дистанційного керування роботами",
        text4: "Розробка та запуск повністю автономних роботів — це тривалий і дорогий процес. Навіть після початку роботи, одного разу вони стикаються з перешкодами, на які їх не запрограмували і не навчили долати.",
        text5: "Досвідчені віддалені пілоти допомагають роботу продовжувати свою місію, проводячи його вручну через складні ділянки. Потім робот продовжує працювати сам. Дані автоматично збираються та використовуються для оновлення ШІ робота, щоб зробити його розумнішим.",
        text6: "Недосконалий ШІ не повинен зупиняти ваш бізнес. Підтримка усе вирішує.",
        header3: "Доцільність автоматизації",
        text7: "Перш ніж вкладати значні інвестиції в автоматизацію, можна оцінити ризики та можливості за допомогою консультацій із фіксованою ціною.",
        text8: "Ми використовуємо дизайнерське мислення і надаємо техніко-економічне обгрунтування даних, щоб ви мали всю інформацію для зваженого прийняття рішення.",
        solution: "Розробка проекту автоматизації",
        camera: "Камера на",
        camera2: "робочому місці",
        cloud: "Обробка",
        cloud2: "в хмарі",
        analysis: "Аналіз",
        automation: "Розробка",
        design: "проекту", 
        insights: "Висновки, ідеї, пропозиції",
        requirements: "Рекомендації для автоматизації",
        header4: "Розробка проекту автоматизації",
        text9: "Автоматизацію на основі ШІ складно зробити самостійно. Тут слід врахувати такі аспекти: постачальник штучного інтелекту, системний інтегратор, хмарна інфраструктура, обслуговування.",
        text10: "Наша досвідчена команда може допомогти вам зрозуміти горизонт сучасних можливостей автоматизації та підібрати оптимальне рішення для вашого бізнесу.",
        text11: "Ми даємо можливість роботам і людям безпечно працювати разом.",
        header5: "Автоматизуйте свій бізнес зараз, зв’яжіться з нами",
        uploadVideo: "Завантажте відео вашого робочого процесу",
        addFiles: "Додати відео",
        submitBtn: "ВІДПРАВИТИ",
        name: "Ваше ім'я",
        email: "Ваш E-mail",
        reserved: "Всі права захищені.",
    },
    de: {
        btnStarted: "STARTEN", 
        header1: "Service für Fernbedienung der Roboter",
        text1: "Intelligenter Roboter im Dienste Ihres Geschäftes – das ist der heutige Tag. Unbemannte mobile Lagerplattformen und Manipulatoren komplettieren schon jetzt die Bestellungen, transportieren Güter und erfüllen viele andere nützliche Arbeiten.",
        text2: "Wir sichern eine zuverlässige Funktion der roboterunterstützten Systeme mit künstlicher Intelligenz durch Fernmonitoring und direkte Führung.",
        text3: "Ein erfahrener Führer, der kontinuierlich über 'Roboteraugen' den Prozess überwacht, kann schnell ein Hindernis auslassen, eine komplizierte Bestellung zusammenstellen oder Wartungspersonal rufen.",
        header2: "Service für Fernbedienung der Roboter",
        text4: "Entwicklung und Start der vollselbständigen Roboter sind als dauerhafter und teurer Prozess. Sogar nach dem Arbeitsanfang, stoßen sie einmal auf Hindernisse, für welche sie nicht programmiert wurden und nicht unterrichtet wurden diese zu vermeiden.",
        text5: "Erfahrene Fernführer helfen dem Roboter seine Mission fortzuführen, wobei der Roboter manuell durch komplizierte Strecken geführt wird. Dann arbeitet der Roboter weiter selbständig. Die Daten werden automatisch gesammelt und zur Aktualisierung des künstlichen Roboterintellekts verwendet um den Roboter klüger zu machen.",
        text6: "Ein mangelhafter künstlicher Intellekt soll Ihr Business nicht stoppen. Die Unterstützung ist hier eine perfekte Lösung.",
        header3: "Zweckdienlichkeit der Automatisierung",
        text7: "Bevor Sie bedeutende Investitionen in Automatisierung vornehmen, können Sie durch eine Festpreis-Beratung Ihre Risiken und Möglichkeiten beurteilen.",
        text8: "Wir setzen Designdenken ein und stellen Ihnen technisch-ökonomische Begründung von Daten zur Verfügung, damit Sie sämtliche Informationen zur ausgewogenen Entscheidung haben.",
        solution: "Lösungsentwicklung",
        camera: "Kamera auf",
        camera2: "dem Arbeitsplatz",
        cloud: "Bearbeitung",
        cloud2: "in der Wolke",
        analysis: "Analyse",
        automation: "Projektentwicklung",
        insights: "Einblicke",
        requirements: "Anforderungen",
        header4: "Lösungsentwicklung",
        text9: "Es ist kompliziert, die Automatisierung auf der Grundlage der künstlichen Intelligenz selbständig durchzuführen. Hier sind folgende Aspekte zu berücksichtigen: Lieferant des künstlichen Intellektes, Systemintegrator, Wolken-Infrastruktur, Service.",
        text10: "Unser erfahrenes Team kann Ihnen helfen, den Stand der heutigen Möglichkeiten in der Automatisierung zu verstehen und eine optimale Lösung für Ihr Business zu wählen.",
        text11: "Wir geben den Robotern und Menschen eine Möglichkeit gefahrlos zusammen zu arbeiten.",
        header5: "Automatisieren Sie Ihr Business jetzt, kontaktieren Sie uns",
        uploadVideo: "Das Hochladen von Videos aus Ihrem Prozess ist vollständig gestartet",
        addFiles: "Aus dem Video",
        submitBtn: "SENDEN",
        name: "Dein Name",
        email: "Deine E-Mail",
        reserved: "All rights reserved.",
    },
    pl: {
        btnStarted: "ROZPOCZĄĆ",
        header1: "Zdalne sterowania robotów", 
        text1: "Roboty ze sztuczną inteligencją w służbie Twojego biznesu to teraźniejszość. Bezzałogowe mobilne platformy magazynowe i manipulatory już realizują zamówienia, transportują towary i wykonują wiele innych pożytecznych prac.",
        text2: "Podczas pracy sztuczna inteligencja (SI) inteligentnych maszyn napotyka czasem sytuacje, które wcześniej nie były znane twórcom. Na przykład, robot ładujący nie może ominąć nowego rodzaju przeszkody i zatrzymuje się. Zwlekanie z rozwiązywaniem takich problemów może skutkować nieprzewidywalnymi opóźnieniami w procesie produkcyjnym.",
        text3: "Zapewniamy niezawodne działanie zrobotyzowanych systemów SI poprzez zdalny monitoring i bezpośrednie pilotowanie.Doświadczony pilot, który na bieżąco monitoruje przebieg pracy 'oczami robota' jest w stanie szybko ominąć przeszkodę, odebrać złożone zamówienie czy wezwać obsługę techniczną.",
        header2: "Usługa zdalnego sterowania robotów",
        text4: "Opracowywanie i uruchamianie w pełni autonomicznych robotów to długi i kosztowny proces. Nawet po rozpoczęciu pracy pewnego dnia one napotykają przeszkody, do pokonywania których nie zostały zaprogramowane i nauczone.",
        text5: "Doświadczeni piloci zdalni pomagają robotowi w kontynuowaniu misji, prowadząc go ręcznie przez trudne obszary. Następnie robot sam kontynuuje pracę. Dane są zbierane automatycznie i wykorzystywane do aktualizacji SI robota, aby uczynić go inteligentniejszym.",
        text6: "Niedoskonała sztuczna inteligencja nie powinna powstrzymywać Twojego biznesu. Wsparcie rozwiązuje wszystkie problemy.",
        header3: "Studium wykonalności",
        text7: "Zanim zainwestujesz znacząco w automatyzację, możesz ocenić ryzyko i szanse poprzez konsultację ze stałą ceną.",
        text8: "Korzystamy z myślenia projektowego i zapewniamy ocenę i analizę potencjału projektu, abyś miał wszystkie informacje do podjęcia świadomej decyzji.",
        solution: "Opracowanie projektu automatyzacji",
        camera: "Kamera w",
        camera2: "miejscu pracy",
        cloud: "Przetwarzanie",
        cloud2: "w chmurze",
        analysis: "Analiza",
        automation: "Projektowanie",
        design: "automatyki",
        insights: "Wnioski, pomysły, sugestie",
        requirements: "Wymagania",
        header4: "Opracowanie projektu automatyzacji",
        text9: "Automatyzacja oparta na sztucznej inteligencji jest trudna do wykonania samodzielnie. Należy wziąć pod uwagę następujące aspekty: dostawca sztucznej inteligencji, integrator systemów, infrastruktura chmurowa, obsługiwanie.",
        text10: "Umożliwiamy bezpieczną współpracę robotów i ludzi",
        text11: "Umożliwiamy bezpieczną współpracę robotów i ludzi.",
        header5: "Zautomatyzuj swój biznes już teraz, skontaktuj się z nami",
        uploadVideo: "Prześlij wideo/nagranie swojego procesu pracy",
        addFiles: "Dodaj wideo",
        submitBtn: "WYSŁAĆ",
        name: "Imię",
        email: "E-mail",
        reserved: "Wszelkie prawa zastrzeżone.",
    },
}